# Generated by Django 4.1.6 on 2023-02-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VentaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=11)),
                ('razon_social', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.ventamodel')),
            ],
            options={
                'db_table': 'detalles_venta',
            },
        ),
    ]
